### ISSUE TITLE
Do you continue this project?

### ISSUE THREAD

**Issue by ghost** [woctezuma/steam-IJEPA#1]
Hi, your project is really interesting.
I wonder if you are still continuing to work on this project or not. Your sharing will help me a lot, thank you so much.

**Comment by woctezuma** [comment]
Thank you for your interest.

I have put the project on hold for now:
1. due to lack of time,
2. because I had trouble running the model on Google Colab.

Meanwhile, you can have a look at [another project of mine](https://github.com/woctezuma/steam-DINOv2) which uses DINOv2 instead of I-JEPA.

**Comment by ghost** [comment]
Can you share the code on Colab? Maybe I can fix that. Thanks

**Comment by woctezuma** [comment]
Unfortunately, I cannot find the code. I believe I deleted it when it failed. I would have to look at [this script](https://github.com/facebookresearch/ijepa/blob/main/main.py) again.

Probably:

https://github.com/facebookresearch/ijepa/blob/52c1ae95d05f743e000e8f10a1f3a79b10cff048/src/train.py#L161-L169

https://github.com/facebookresearch/ijepa/blob/52c1ae95d05f743e000e8f10a1f3a79b10cff048/src/train.py#L234-L241

etc.
